apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: unitflix
data:
  Image__url: "http://77.37.122.17:8080/backend"
  JWT__ValidAudience: "http://77.37.122.17:8080/backend"
  JWT__ValidIssuer: "http://77.37.122.17:8080/backend"