apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: unitflix
data:
  Image__url: "https://unitflix.com/backend"
  JWT__ValidAudience: "https://unitflix.com"
  JWT__ValidIssuer: "https://unitflix.com"