apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: unitflix
data:
  Image__url: "http://unitflix.localhost/backend"
  JWT__ValidAudience: "http://unitflix.localhost/backend"
  JWT__ValidIssuer: "http://unitflix.localhost/backend"