apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: unitflix
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "1024m"
spec:
  ingressClassName: nginx
  rules:
    - host: unitflix.localhost
      http:
        paths:
          - path: /backend
            pathType: Prefix
            backend: 
              service:
                name: backend-srv
                port:
                  number: 5074
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-srv
                port:
                  number: 5173