apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: unitflix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      initContainers:
      - name: fix-mssql-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 10001:0 /var/opt/mssql"]
        volumeMounts:
          - name: db-volume
            mountPath: /var/opt/mssql
      containers:
        - name: db
          image: asimwattoo/unitflix-db:latest
          ports:
            - containerPort: 1433
          envFrom:
            - configMapRef:
                name: db-config
            - secretRef:
                name: db-secrets
          volumeMounts:
            - name: db-volume
              mountPath: /var/opt/mssql
      volumes:
        - name: db-volume
          persistentVolumeClaim:
            claimName: db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: db-srv
  namespace: unitflix
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
      nodePort: 30605
  type: LoadBalancer
  loadBalancerIP: 77.37.122.17